SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
	ROUND(COUNT(DISTINCT U.USER_ID) / (
			SELECT COUNT(*)
			FROM USER_INFO I
			WHERE EXTRACT(YEAR FROM I.JOINED) = 2021
		), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE EXTRACT(YEAR FROM U.JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY YEAR, MONTH